import time
print("\r Loading: [#         ] 10%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [##        ] 20%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [###       ] 30%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [####      ] 40%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [#####     ] 50%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [######    ] 60%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [#######   ] 70%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [########  ] 80%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [######### ] 90%", end = "\r") 
time.sleep(0.5)
print("\r Loading: [##########] 100% - Finished!", end = "\r") 
time.sleep(0.5)